### PR TITLE
Remove 470 transitional packaging to allow it to be installed for legacy products

### PR DESCRIPTION
**Pull request by jackpot51**
There may be issues with the expected installation method (Pop!\_Shop) that we need to address.

### CODE REVIEW

**Review by mmstick — APPROVED** [review]

**Comment by XV-02** [comment]
This doesn't seem to have taken. With the nvidia-510.54 branch added, the 470 package still shows as a transitional package.

`nvidia-driver-470/impish 510.54-1pop0~1645544462~21.10~e35d257 amd64
  Transitional package for nvidia-driver-510
`

**Comment by Redbatman89** [comment]
510.54 is not appearing for POP OS 20.04

**Comment by jackpot51** [comment]
@XV-02 we will have to release this for it to work. To test it prior to release, you will have to disable the release repository and only use the staging repository

**Comment by XV-02** [comment]
The 470 driver is now explicitly installable, and is installable from both Pop!_shop and apt.

**Pull request merged**
