### PR TITLE
NVIDIA 515.48.07

### PR DESCRIPTION
**Pull request by jackpot51**
https://www.nvidia.com/Download/driverResults.aspx/189809/en-us

I have undone some changes we have compared to Ubuntu packaging that I think are no longer needed. Standard testing with hybrid graphics will ensure those changes are correct.

### CODE REVIEW

**Review by linuxgnuru — APPROVED** [review]
All testing passed for gaze16-3050ti on 22.04.

[nvidia-515.48.07_gaze16-3050ti.txt](https://github.com/pop-os/nvidia-graphics-drivers/files/8835531/nvidia-515.48.07_gaze16-3050ti.txt)

**Comment by jackpot51** [comment]
This is a major version bump, good to test as much as possible.

**Comment by linuxgnuru** [comment]
Yeah sorry about that; won't happen again.

Here's the results from kudu6 (3060) and thelio r1-6 (1070)

On the kudu6 in hybrid mode with lid closed the system was pretty much unusable but this is also present with 510 drivers.

[nvidia-515.48.07_kudu6.txt](https://github.com/pop-os/nvidia-graphics-drivers/files/8846165/nvidia-515.48.07_kudu6.txt)
[nvidia-515.48.07_thelio-r1-6-1070.txt](https://github.com/pop-os/nvidia-graphics-drivers/files/8846166/nvidia-515.48.07_thelio-r1-6-1070.txt)

**Comment by n3m0-22** [comment]
- All tests passed `gaze15` `22.04` and `21.10`
- All tests passed except for fractional scaling on external display over mDP `gaze15` `20.04`
- All tests passed `orpy4` `22.04`
- All tests passed except for fractional scaling on external display over HDMI and mDP `orpy4` `20.04` and `21.10`

[20.04_515.48.07_gaze15.txt](https://github.com/pop-os/nvidia-graphics-drivers/files/8846279/20.04_515.48.07_gaze15.txt)
[21.10_515.48.07_gaze15.txt](https://github.com/pop-os/nvidia-graphics-drivers/files/8846280/21.10_515.48.07_gaze15.txt)
[20.04_515.48.07_orpy4.txt](https://github.com/pop-os/nvidia-graphics-drivers/files/8846282/20.04_515.48.07_orpy4.txt)
[21.10_515.48.07_orpy4.txt](https://github.com/pop-os/nvidia-graphics-drivers/files/8846283/21.10_515.48.07_orpy4.txt)
[22.04_515.48.07_orpy4.txt](https://github.com/pop-os/nvidia-graphics-drivers/files/8846284/22.04_515.48.07_orpy4.txt)

**Comment by leviport** [comment]
>On the kudu6 in hybrid mode with lid closed the system was pretty much unusable but this is also present with 510 drivers.

@linuxgnuru did you say this worked better than 510 on a Gazelle though?

**Comment by leviport** [comment]
We need to check this on Ubuntu 22.04. If that looks good, we can approve it.

**Comment by bflanagin** [comment]
Ubuntu 22.04 on galp5 tests all come back as expected.

**Review by leviport — APPROVED** [review]
Approving, but we might want to hold off on releasing until Monday.

**Comment by jackpot51** [comment]
I'm gonna have it build but not release until Monday, along with some other queued changes.

**Pull request merged**
