### PR TITLE
460.39

### PR DESCRIPTION
**Pull request by jackpot51**
https://www.nvidia.com/Download/driverResults.aspx/170134

### CODE REVIEW

**Review by bflanagin — COMMENTED** [review]
Tested on gaze15 passed on Pop 20.10 20.04 and Ubuntu 20.04.1

[nvidia_pr87_gaze15_pop_focal.txt](https://github.com/pop-os/nvidia-graphics-drivers/files/5883371/nvidia_pr87_gaze15_pop_focal.txt)
[nvidia_pr87_gaze15_pop_groovy.txt](https://github.com/pop-os/nvidia-graphics-drivers/files/5883372/nvidia_pr87_gaze15_pop_groovy.txt)
[nvidia_pr87_gaze15_ubuntu_focal.txt](https://github.com/pop-os/nvidia-graphics-drivers/files/5883373/nvidia_pr87_gaze15_ubuntu_focal.txt)

**Comment by jackpot51** [comment]
I assume we need more testing for a @pop-os/quality-assurance approval, right?

**Comment by leviport** [comment]
Yeah, gaze15 is the only machine @bflanagin has at his disposal so we have a little more checking to do before we can bless it.

**Review by jacobgkau — APPROVED** [review]
Tested graphics, compute, graphics switching (where applicable), external display with audio, and suspend/resume while playing Firefox video on galp5, serw12, and thelio-b1.6 w/ 2060 Super.

Had an issue with compute mode on galp5, but confirmed that it's not caused by this particular update: https://github.com/pop-os/nvidia-graphics-drivers/issues/88 

Levi also checked 2x 2080 Supers in thelio-major-b3 and there were no issues there.

**Pull request merged**
