### PR TITLE
NVIDIA 515.65.01

### PR DESCRIPTION
**Pull request by 13r0ck**

### CODE REVIEW

**Comment by gangwerz** [comment]
Driver passed testing on the galp5-1650Ti with Pop/Ubuntu 20.04 & 22.04

A couple ongoing Ubuntu issues were seen:
- Steam continues to not launch from the app menu, but does launch from a Terminal.
- Proton Experimental throws an error when you launch a game. Switching to a versioned release addresses the behavior.

[515.65.01-pr159.txt](https://github.com/pop-os/nvidia-graphics-drivers/files/9419184/515.65.01-pr159.txt)

**Review by gangwerz — APPROVED** [review]
:+1: :rocket:

**Comment by linuxgnuru** [comment]
> Driver passed testing on the galp5-1650Ti with Pop/Ubuntu 20.04 & 22.04
> 
> A couple ongoing Ubuntu issues were seen:
> 
> * Steam continues to not launch from the app menu, but does launch from a Terminal.
> * Proton Experimental throws an error when you launch a game. Switching to a versioned release addresses the behavior.
> 
> [515.65.01-pr159.txt](https://github.com/pop-os/nvidia-graphics-drivers/files/9419184/515.65.01-pr159.txt)

ubuntu has had issues if in nvidia or hybrid trying to run anything with dedicated GPU (blender also crashes)

**Comment by linuxgnuru** [comment]
Pop 22.04 oryp9

## Testing
This document provides a guideline for testing and verifying NVIDIA driver updates. Copy this checklist and mark items as they are verified to work.

These tests _must_ be performed on every OS version that the driver will be released on. Typically, that will be the Pop!\_OS regular release, the Pop!\_OS LTS, and the Ubuntu LTS.

## Installation

Add the staging branch containing the updated driver with the [apt script](https://github.com/pop-os/pop/blob/master/scripts/apt) in the pop-os/pop repo.

- [x] `sudo apt upgrade` updates the driver without conflicts (Ubuntu may require `full-upgrade`).

## Laptop graphics (switchable graphics)

Switchable graphics laptops can render with either the CPU-integrated GPU or the dedicated NVIDIA GPU. Before installing the driver update, make sure the machine is in Hybrid graphics mode.

- [x] After update and reboot, the machine remained in Hybrid graphics mode.

### Hybrid mode tests

- [x] Laptop suspends and resumes (works with a bluetooth device paired)
- [x] `nvidia-smi` correctly reports the GPU's status
- [x] DisplayPort (mDP and DP over USB-C) outputs (including sound) work as expected
- [x] HDMI-out (including sound) works as expected
- [x] External display becomes primary display when laptop lid is closed
- [x] HDMI-out fractional scaling on external monitor works at 125%, 150%, 175%
- [x] DisplayPort (mDP and DP over USB-C) fractional scaling on external monitor works at 125%, 150%, 175%
- [x] Steam can be installed and launched
  - [x] From Launcher
  - [x] From App Library
  - [x] From Dock
  - [x] From Terminal
- [x] A native Linux game can be launched from Steam
- [x] A Proton game can be launched from Steam

NOTES: for HDMI fractional scaling to work I had to use a 4k display

### NVIDIA mode tests

- [x] Laptop suspends and resumes (works with a bluetooth device paired)
- [x] `nvidia-smi` correctly reports the GPU's status
- [x] DisplayPort (mDP and DP over USB-C) outputs (including sound) work as expected
- [x] HDMI-out (including sound) works as expected
- [x] External display becomes primary display when laptop lid is closed
- [x] HDMI-out fractional scaling on external monitor works at 125%, 150%, 175%
- [x] DisplayPort (mDP and DP over USB-C) fractional scaling on external monitor works at 125%, 150%, 175%
- [x] Steam can be installed and launched
  - [x] From Launcher
  - [x] From App Library
  - [x] From Dock
  - [x] From Terminal
- [x] A native Linux game can be launched from Steam
- [x] A Proton game can be launched from Steam

NOTES: for HDMI fractional scaling to work I had to use a 4k display

### Compute mode tests

- [x] `nvidia-smi` correctly reports the GPU's status
- [x] Plugging in a display correctly prompts to switch to Hybrid mode

### Integrated mode test

- [x] Plugging in a display correctly prompts to switch to Hybrid mode
- [x] Steam can be installed and launched
  - [x] From Launcher
  - [x] From App Library
  - [x] From Dock
  - [x] From Terminal
- [x] A native Linux game can be launched from Steam
- [x] A Proton game can be launched from Steam

## Software tests

These can be done on any machine with an NVIDIA GPU

- [x] NVIDIA X Server Settings application launches properly
- [x] A Unigine benchmark performs as expected

**Comment by leviport** [comment]
This is looking good on Pop 22.04 on mira-b3 with a 2080. I'd like to test another Nvidia desktop with Ubuntu 22.04 as well, then it should be good to go.

**Review by mmstick — APPROVED** [review]

**Comment by XV-02** [comment]
@leviport This played nicely on the Mega R2 with 3060Ti under Ubuntu - I'd be comfortable releasing this if a desktop Ubuntu check was the last thing you were looking for.

**Comment by leviport** [comment]
Yeah, that's what my comment said.

**Review by leviport — APPROVED** [review]

**Pull request merged**
