### PR TITLE
465.24.02: https://www.nvidia.com/Download/driverResults.aspx/172836/en-us

### PR DESCRIPTION
**Pull request by mmstick**

### CODE REVIEW

**Comment by jacobgkau** [comment]
- [X] Installs with a regular `apt upgrade`.
-  oryp7 OLED (3070):
    - [X] Graphics
    - [X] Compute
    - [X] Display configuration & audio through display
    - [X] Suspend/resume, including while playing Firefox video
    - [ ] Graphics switching & modes (Compute mode issue was pre-existing: https://github.com/system76/firmware-open/issues/160)
- serw12 (1660 Ti):
    - [X] Graphics
    - [X] Compute
    - [X] Display configuration & audio through display
    - [X] Suspend/resume, including while playing Firefox video
- galp5 (1650):
    - [X] Graphics
    - [X] Compute
    - [X] Display configuration & audio through display
    - [X] Suspend/resume, including while playing Firefox video
    - [X] Graphics switching & modes

Looking fine on laptops.

**Comment by bflanagin** [comment]
No regressions detected on Gaze15 (1660 Ti)

**Review by leviport — APPROVED** [review]
Tested on thelio-massive-b1 w/2080Ti and thelio-b2 w/3060Ti. Both are working as expected.

**Review by crawfxrd — APPROVED** [review]

**Comment by S-C-Johnston** [comment]
For posterity, I want to comment that this solves GPU passthrough issues in qemu/kvm virtualization usecases. The linux drivers for revision 465 do actually include the appropriate changes to make virtualization work, rather than only being a Windows driver change.

**Pull request merged**
