### PR TITLE
NVIDIA 545.23.06

### PR DESCRIPTION
**Pull request by mmstick**
https://www.nvidia.com/download/driverResults.aspx/212964/en-us/

### CODE REVIEW

**Comment by rwjack** [comment]
GAMMA_LUT hype!

**Comment by ids1024** [comment]
> 545.23.06 BETA

This seems to be a beta driver, and not a stable release. So I presume we don't want to release this until there's a stable 545 driver. But it's worth seeing how this is currently working anyway.

On my gaze15 with this driver, external monitors (connected to the Nvidia GPU) do not work with cosmic-comp, unlike on 535. That may be a Smithay or cosmic-comp, but we'll want to look into that.

```
Oct 18 17:13:26 pop-os cosmic-comp[9887]: New screen configuration invalid!
[...]
Atomic Test failed for new properties on crtc (crtc::Handle(55))

**Comment by chase** [comment]
545.84 is stable @ids1024:
https://www.nvidia.com/Download/driverResults.aspx/212898/en-us/

**Comment by leviport** [comment]
This driver does appear to fix Starfield. On 535, the game would launch and get me to the main menu, but it always froze at the loading screen when I tried to enter the game. With this beta 545 driver, it got past the loading screen just fine.

**Pull request closed without merging**
