### PR TITLE
release: 455.45

### PR DESCRIPTION
**Pull request by mmstick**
https://www.nvidia.com/en-us/drivers/results/166883/

### CODE REVIEW

**Review by jackpot51 — APPROVED** [review]

**Comment by OneWithTheCore** [comment]
Any update on when this updated driver will be made available?

**Review by leviport — APPROVED** [review]
This is looking good from my testing, but let's not release it until after the holiday.

**Comment by leviport** [comment]
@OneWithTheCore It's just about ready, but it hasn't been terribly high priority since the main thing it adds for us is 3060Ti support, for which there is still very low availability. We'll most likely be releasing it next week.

**Comment by OneWithTheCore** [comment]
@leviport Thank you for the update and the work on this

**Comment by varomix** [comment]
when can we have this version, need this to use Kernel 5.9 to resolve battery/power related issues, thank you

**Pull request merged**
