### PR TITLE
Update to 430.14

### PR DESCRIPTION
**Pull request by jackpot51**
https://www.nvidia.com/Download/driverResults.aspx/147582/en-us

### CODE REVIEW

**Comment by mmstick** [comment]
Successfully upgraded on oryp2 and thelio

Screenshot from 2019-05-14 15-31-38

Required `apt full-upgrade`, but otherwise worked.

**Comment by jackpot51** [comment]
The packaging issues with this will be addressed later. For now the critical issue is with tearing, which will need to be fixed somehow in gdm3

**Comment by jackpot51** [comment]
Adding i386 support the the CI should fix any issues with the packaging

**Comment by jackpot51** [comment]
Our Ubuntu images don't have i386 architecture installed, causing upgrade failures! :(

**Comment by rstrube** [comment]
I'm curious what the progress is on this PR.  Valve's new version of steamplay doesn't perform well with the older 418.56 driver, so it would be fantastic to move to 430.14.

**Comment by mmstick** [comment]
Progress is done when it's done :P We can't release new driver packages until everything works on Ubuntu 18.04, Pop 18.04, and Pop 19.10. Having issues with Ubuntu images right now.

**Comment by rstrube** [comment]
> Progress is done when it's done :P We can't release new driver packages until everything works on Ubuntu 18.04, Pop 18.04, and Pop 19.04. Having issues with Ubuntu images right now.

Ahh that's too bad.  The LTS is holding up progress! :)

I'm currently running 19.04 on a Darter Pro 2019, do you think it would be safe for me to get the latest packages via:

```
sudo add-apt-repository ppa:system76/proposed
sudo apt update
sudo apt upgrade
```

Also does the 430.14 package include the work you guys did on 418.56 to enable modesetting?

Thank you!

**Comment by brs17** [comment]
> > Progress is done when it's done :P We can't release new driver packages until everything works on Ubuntu 18.04, Pop 18.04, and Pop 19.04. Having issues with Ubuntu images right now.
> 
> Ahh that's too bad. The LTS is holding up progress! :)
> 
> I'm currently running 19.04 on a Darter Pro 2019, do you think it would be safe for me to get the latest packages via:
> 
> ```
> sudo add-apt-repository ppa:system76/proposed
> sudo apt update
> sudo apt upgrade
> ```
> 
> Also does the 430.14 package include the work you guys did on 418.56 to enable modesetting?
> 
> Thank you!

Sounds like you might be a little confused. The Darter Pro does not have NVIDIA graphics so none of this should really affect you at all.

**Comment by rstrube** [comment]
> > > Progress is done when it's done :P We can't release new driver packages until everything works on Ubuntu 18.04, Pop 18.04, and Pop 19.04. Having issues with Ubuntu images right now.
> > 
> > 
> > Ahh that's too bad. The LTS is holding up progress! :)
> > I'm currently running 19.04 on a Darter Pro 2019, do you think it would be safe for me to get the latest packages via:
> > ```
> > sudo add-apt-repository ppa:system76/proposed
> > sudo apt update
> > sudo apt upgrade
> > ```
> > 
> > 
> > Also does the 430.14 package include the work you guys did on 418.56 to enable modesetting?
> > Thank you!
> 
> Sounds like you might be a little confused. The Darter Pro does not have NVIDIA graphics so none of this should really affect you at all.

I probably should have explained that I'm running an RTX 2070 as an eGPU over Thunderbolt 3 on my Darter Pro 2019.  It's been running fantastic actually and gaming performance with native Linux games has been really solid.  Proton just has some performance issues with 418.56, hence my interest.

**Comment by mmstick** [comment]
@rstrube Interesting. What are you using for that setup?

**Comment by rstrube** [comment]
> @rstrube Interesting. What are you using for that setup?

I'm using an Akitio Node: https://www.akitio.com/expansion/node

It also supports firmware updates via LVFS which is fantastic!

```
fwupdmgr get-devices
N15xZU Thunderbolt Controller
  DeviceId:             c918b29576a1285ea1d696c76d073b4aaf18b690
  Guid:                 35403ef7-d49c-53ed-8008-1c0b5d3f1360
  Summary:              Unmatched performance for high-speed I/O
  Plugin:               thunderbolt
  Flags:                internal|updatable|registered
  Vendor:               Clevo
  VendorId:             TBT:0x00CD
  Version:              36.00
  Icon:                 computer
  Created:              2019-05-21

AKiTiO Node
  DeviceId:             6de9ef953ae1b0e66574e2b45623db75093ff083
  Guid:                 c6da27ea-e8f8-5b21-9c80-5bd3a310b4da
  Plugin:               thunderbolt
  Flags:                updatable|registered
  Vendor:               inXtron
  VendorId:             TBT:0x0041
  Version:              25.00
  Icon:                 audio-card
  Created:              2019-05-21
```

**Comment by Amplespencer** [comment]
I added the proposed PPA but I don't see an upgrade for the new driver
**here's relevant parts of neofetch**
OS: Ubuntu 19.04 x86_64 (why is this still broken? ubuntu logo too!)
Kernel: 5.0.0-13-generic 
Shell: bash 5.0.3 
Resolution: 2560x1080 
Terminal: gnome-terminal (I normally use qterminal but I'm reinstalling so my / partition is bigger)
CPU: Intel i7-7700K (8) @ 4.500GHz 
GPU: NVIDIA GeForce GTX 970 
Memory: 1491MiB / 15985MiB 

I checked /etc/apt/sources.list.d and there is the proposed ppa there
I type` sudo apt update`
no errors
`sudo apt upgrade`
shows a few random packages like gnome calendar

What am I doing wrong? I would just run it as a deb file from the repo but 7z doesn't like some stuff in the control file

**Comment by rstrube** [comment]
> I added the proposed PPA but I don't see an upgrade for the new driver
> **here's relevant parts of neofetch**
> OS: Ubuntu 19.04 x86_64 (why is this still broken? ubuntu logo too!)
> Kernel: 5.0.0-13-generic
> Shell: bash 5.0.3
> Resolution: 2560x1080
> Terminal: gnome-terminal (I normally use qterminal but I'm reinstalling so my / partition is bigger)
> CPU: Intel i7-7700K (8) @ 4.500GHz
> GPU: NVIDIA GeForce GTX 970
> Memory: 1491MiB / 15985MiB
> 
> I checked /etc/apt/sources.list.d and there is the proposed ppa there
> I type` sudo apt update`
> no errors
> `sudo apt upgrade`
> shows a few random packages like gnome calendar
> 
> What am I doing wrong? I would just run it as a deb file from the repo but 7z doesn't like some stuff in the control file

Perhaps the packages in question haven't landed in the proposed PPA yet? Not sure.  I'm hoping the Pop!_OS engineering team is able to get these out soon though!

**Comment by Amplespencer** [comment]
Yeah I would really like to get this update

**Comment by rstrube** [comment]
@Amplespencer check out the proposed PPA here: https://launchpad.net/~system76/+archive/ubuntu/proposed
Indeed the 418 driver is the latest in proposed, so you're not going crazy!

**Comment by jackpot51** [comment]
Try this:


```
sudo add-apt-repository "deb http://apt.pop-os.org/staging/430.14 $(lsb_release -cs) main"
```

**Comment by Amplespencer** [comment]
thank you that worked

**Comment by jackpot51** [comment]
With two NVIDIA RTX 2080 Ti's connected with an NVLink bridge, I got this error:

```
Jun 21 15:14:03 jeremy-work kernel: NVRM: GPU at PCI:0000:65:00: GPU-241118b6-510b-b4da-059e-434d25c4df3b
Jun 21 15:14:03 jeremy-work kernel: NVRM: GPU Board Serial Number: 
Jun 21 15:14:03 jeremy-work kernel: NVRM: Xid (PCI:0000:65:00): 16, Head 00000000 Count 0000070c
```

**Comment by jackpot51** [comment]
This work will be continued on #9

**Pull request closed without merging**
