### PR TITLE
460.32

### PR DESCRIPTION
**Pull request by jackpot51**
Must be tested with galp5, may allow galp5 hybrid workaround to be removed

### CODE REVIEW

**Comment by jackpot51** [comment]
The galp5 appears to work in Hybrid mode without the DynamicPowerManagement workaround with this driver

**Comment by jackpot51** [comment]
Suspend hangs on the galp5 with or without NVreg_EnableS0ixPowerManagement=1

galp5-suspend-hang

**Comment by jackpot51** [comment]
I have modified the nvidia-driver-460 package to include the systemd services mentioned in http://us.download.nvidia.com/XFree86/Linux-x86_64/460.32.03/README/powermanagement.html

This appears to fix suspend/resume on the galp5

**Comment by jackpot51** [comment]
I noticed a minor issue with the packaging, fixed in the last force push. This should be ready to review again.

**Review by mmstick — APPROVED** [review]

**Review by jacobgkau — APPROVED** [review]
This fixes all known issues on galp5. After applying https://github.com/pop-os/system76-driver/pull/189 together with this branch, I'm no longer seeing the dGPU crashes upon unplugging while the dGPU is suspended in hybrid mode. Suspend/resume is still working reliably.

Tested graphics, compute, external display with audio, and suspend/resume while playing Firefox video on galp5, serw12, addw2, and thelio-b1.6 w/ 2060 Super (also tested compute & hybrid modes on the switchable machines.) Levi also tested on major-b3 w/ 2x 2080's.

**Pull request merged**
