### PR TITLE
Nvidia 535.86.05

### PR DESCRIPTION
**Pull request by mmstick**
https://www.nvidia.com/Download/driverResults.aspx/209261/en-us/

Supersedes #184

### CODE REVIEW

**Comment by gabriele2000** [comment]
Heh, another testing batch?

**Comment by ahoneybun** [comment]
I added this repo, upgraded and did not see the screen go black like the earlier driver in the other PR.

**Comment by leviport** [comment]
> I added this repo, upgraded and did not see the screen go black like the earlier driver in the other PR.

Yeah, Michael fixed that in the last PR

**Review by XV-02 — APPROVED** [review]
On Pop and Ubuntu both, I'm not seeing regressions, and haven't found any issues running through our checklist on both. In particular, I'm not seeing performance regressions. Benchmarks are consistent, testing in games has been consistent, and I'm not noticing any flickering or other issues I've seen reported in the Linux space at large. 


So, I'm calling this good to go.

**Review by jackpot51 — DISMISSED** [review]

**Review by jackpot51 — APPROVED** [review]

**Pull request merged**
