### PR TITLE
460.80: https://www.nvidia.com/Download/driverResults.aspx/175203/en-us

### PR DESCRIPTION
**Pull request by mmstick**

### CODE REVIEW

**Review by jackpot51 — APPROVED** [review]

**Comment by bflanagin** [comment]
Like @ahoneybun reported in slack the driver is installed but pop_shop still shows that it needs to be installed.

Screenshot from 2021-05-17 16-02-46

**Comment by bflanagin** [comment]
When in compute mode Blender froze up when switching to gpu-compute. Xorg is now unable to start after reboot. Logs attached.

[Xorg.0.log](https://github.com/pop-os/nvidia-graphics-drivers/files/6503081/Xorg.0.log)
[Xorg.1.log](https://github.com/pop-os/nvidia-graphics-drivers/files/6503082/Xorg.1.log)

**Comment by bflanagin** [comment]
Gaze15 1660 ti - Pop 20.10

## Standard Tests

- [x] installs 

## Single display 

- [x] Hybrid Mode
- [x] Dedicated Mode
- [x] Integraded Mode
- [x] Compute Mode

## Multiple Displays

- [x] Hybrid Mode
- [x] Dedicated Mode

- [ ] Integrated mode
- [ ] Compute Mode

## Software tests

- [x] Steam client launches, 32bit proton game works
- [x] Graphics accelerated Flatpak works 

## Suspend tests: to test for screen corruption
- [ ] Hybrid (still needs testing)
- [ ] Integrated (still needs testing)
- [x] Dedicated

**Comment by jackpot51** [comment]
Obsoleted by #106

**Pull request closed without merging**
