### PR TITLE
Update to 430

### PR DESCRIPTION
**Pull request by jackpot51**
This is based on the NVIDIA package from 19.10, and replaces #7.

We need to keep an eye out for package update issues.

- [x] Pop!_OS 18.04
- [x] Pop!_OS 19.04
- [x] Ubuntu 18.04

### CODE REVIEW

**Comment by jackpot51** [comment]
Upgrade on Pop!_OS 19.04 worked.

**Comment by brs17** [comment]
Because this is a newer version than #7, I do want to go through normal NVIDIA regression testing.

**Comment by jackpot51** [comment]
@brs17 that would be good. Want to make a checklist for that?

**Comment by brs17** [comment]
New NVIDIA driver checklist:

Run all tests on following hardware:
- [ ] Current gen NVIDIA in desktop
- [ ] Previous gen NVIDIA
- [ ] Switchable graphics laptop (test switching back and forth, then test NVIDIA below)
- [ ] NVIDIA graphics laptop

Before suspend:
- [ ] Full audio tests (input/output) 
- [ ] Lock screen
- [ ] Plug in all external displays
    - Lock screen
    - Audio out of displays

After suspend:
- [ ] Full audio tests (input/output) 
- [ ] Lock screen
- [ ] Plug in all external displays
    - Lock screen
    - Audio out of displays

- [ ] From cold boot, plug in all external displays
    - Lock screen
    - Audio out of displays (before and after suspend)
    - Suspend/resume
    - Lock screen
    - Audio out of displays (before and after suspend)

**Comment by mmstick** [comment]
**NVIDIA graphics laptop**

Tested on a laptop with only NVIDIA graphics. The displays that I have do not support audio output, however.

## Before Suspend

- [x] Audio tests
  - [x] Audio out of built-in speakers
  - [x] Audio in of built-in microphone
  - [x] Audio out of headphones
  - [x] Audio in of headphones
- [x] Lock Screen
- [x] Plug in all extern displays
  - [x] Lock Screen
  - [ ] Audio out of displays

## After Suspend

- [x] Audio tests
  - [x] Audio out of built-in speakers
  - [x] Audio in of built-in microphone
  - [x] Audio out of headphones
  - [x] Audio in of headphones
- [x] Lock screen
- [x] Plug in all extern displays
  - [x] Lock Screen
  - [ ] Audio out of displays

## Cold boot
 
- [x] Audio tests
  - [x] Audio out of built-in speakers
  - [x] Audio in of built-in microphone
  - [x] Audio out of headphones
  - [x] Audio in of headphones
- [x] Lock screen
- [x] Plug in all extern displays
  - [x] Lock Screen
  - [ ] Audio out of displays

**Comment by jackpot51** [comment]
@mmstick @brs17 version has been updated to 430.34

**Comment by rstrube** [comment]
Hi All,

I wanted to add that I've been using 430.34 from the 430 staging repo and I've been having no problems at all.  This includes both gaming, and desktop performance.  I'm running 19.04 Pop_OS on a Darter Pro 2019 with a GTX 2070 as an eGPU via Thunderbolt 3.  I realize this isn't your typical use case, but I thought I would report my experience nonetheless.

**Pull request merged**
