### PR TITLE
NVIDIA 525.116.04

### PR DESCRIPTION
**Pull request by 13r0ck**
https://www.nvidia.com/Download/driverResults.aspx/204837/en-us/

### CODE REVIEW

**Comment by jacobgkau** [comment]
On bonw15, HDMI/DP audio options still don't show up until PipeWire is manually restarted. (This is not a regression.)

**Review by n3m0-22 — COMMENTED** [review]
Tested:
 - Pop!_OS 20.04
 - Pop!_OS 22.04
 - Ubuntu 20.04
 - Ubuntu 22.04
 
Tested on:
 - gaze15
 - oryp4
 - GeForce RTX 3060

All testing has passed with the same caveats as before.

 - Pop!_OS 20.04 requires
   *(NVIDIA graphics mode will not run Steam without)*
   - gnome-shell

 - Ubuntu 20.04 requires the following packages
   *(NVIDIA graphics mode will not boot to the desktop without)*
   - gnome-shell
   - plymouth
   - gir1.2-goa-1.0
   - gnome-control-center

Note:
 - *All packages listed can be found in master staging. Testing by manually installing just these packages was without issue.*

<br>
Once the build issues have been resolved and these packages have been released this will be good to approve.

**Comment by 13r0ck** [comment]
@n3m0-22 gnome-shell should be fixed on pop 20.04 now. (I'm not sure how long it takes for the updated PPA to become available on user machaines?) When you have the chance, please let me know if this works now

**Comment by 13r0ck** [comment]
I believe I fixed those packaging issues. Can we please check again if this works on focal pop/ubuntu now please?

**Review by n3m0-22 — APPROVED** [review]
This is now working for Pop 20.04 as well as Ubuntu 20.04. That last of the issues have been resolved by releasing the packages. Looks good to me.

**Review by crawfxrd — APPROVED** [review]

**Pull request merged**
