### PR TITLE
455.23

### PR DESCRIPTION
**Pull request by mmstick**

### CODE REVIEW

**Comment by jackpot51** [comment]
This doesn't have transitional packaging for 450, which would be required for releasing it

**Review by leviport — APPROVED** [review]
This is looking good on gaze15 (1660Ti), oryp6 (2070), and thelio-major-r2 (tested with 1070 and 2080). Hybrid mode still allows external monitors to be used, and things run on the dGPU in hybrid mode as expected. Battery life on oryp6 in hybrid mode was estimated to be around 6hrs in a very informal test.

Jeremy reported an XID error on addw1, but could not make it happen a second time. I'm not sure if that is cause for concern, but I also could not make it happen on the machines I tested, and Jacob also didn't see it on gaze14. @jackpot51 what are your thoughts?

If we're satisfied and want to release this, let's shoot for early next week so we aren't releasing on a Friday.

**Comment by leviport** [comment]
Oh one thing I forgot to mention: I had to use `sudo apt full-upgrade` to install. I'm not sure whether that's a problem or not.

**Comment by mmstick** [comment]
Yes, every NVIDIA driver upgrade requires it. The Pop Shop performs full-upgrade actions, and apt users get notified.

**Comment by leviport** [comment]
One more thing: let's remember to merge https://github.com/pop-os/gnome-shell-extension-system76-power/pull/47 with it too so users aren't prompted to switch to Nvidia when adding monitors.

**Comment by michaelaye** [comment]
still amazed and love that you do your official pop-os dev out in the open on Github, respect!

**Comment by Redbatman89** [comment]
I had to revert back to 440.100, the new driver was making vulkan shaders take too long to process.

**Comment by leviport** [comment]
@Redbatman89 are you talking about when you launch a proton game in steam? It does take a bit (about 7 minutes when I tried it with fallout 4), but that only happens the first time you launch it. It probably needs to reconfigure them for the new driver, but it won't keep doing it every time.

**Comment by jackpot51** [comment]
That may be fixed by the new 455.28 driver. We will be packaging it soon.

**Comment by Redbatman89** [comment]
> @Redbatman89 are you talking about when you launch a proton game in steam? It does take a bit (about 7 minutes when I tried it with fallout 4), but that only happens the first time you launch it. It probably needs to reconfigure them for the new driver, but it won't keep doing it every time.

It wasn't just Proton but actual Linux native games too. Rise of Tomb Raider was taking almost 20 mins and Serious Sam Fusion was taking long too. Thing is that I allow my Steam to process vulkan shaders in the background once I launch steam everytime.

**Pull request merged**
