### PR TITLE
515.57

### PR DESCRIPTION
**Pull request by mmstick**
https://www.nvidia.com/Download/driverResults.aspx/190414/en-us/

### CODE REVIEW

**Comment by n3m0-22** [comment]
Fractional scaling over mDP on extrnal monitor is not working, but this is not a regression. All other tests passed.
[nvidia-515.57-testing.txt](https://github.com/pop-os/nvidia-graphics-drivers/files/9086005/nvidia-515.57-testing.txt)

**Comment by linuxgnuru** [comment]
pop-22.04-Thelio-mira-b3-2080 passed
[nvidia-515.57-testing-mira-b3.txt](https://github.com/pop-os/nvidia-graphics-drivers/files/9096949/nvidia-515.57-testing-mira-b3.txt)

pop-22.04-kudu6-3060: passed except for fractional scaling with mDP and HDMI
[nvidia-515.57-testing-kudu6.txt](https://github.com/pop-os/nvidia-graphics-drivers/files/9096950/nvidia-515.57-testing-kudu6.txt)

**Comment by linuxgnuru** [comment]
in Ubuntu 22.04 on kudu6 while in Nvidia mode steam instantly crashes with a kernel OOPs.  Journal log attached:

[kudu6-journal.log](https://github.com/pop-os/nvidia-graphics-drivers/files/9104448/kudu6-journal.log)

**Comment by n3m0-22** [comment]
Ubuntu 22.04 on gaze15 all tests passed

[gaze15-ubuntu22.04-nvidia-515.57-testing.txt](https://github.com/pop-os/nvidia-graphics-drivers/files/9104949/gaze15-ubuntu22.04-nvidia-515.57-testing.txt)

**Comment by 13r0ck** [comment]
superseded by https://github.com/pop-os/nvidia-graphics-drivers/pull/159

**Pull request closed without merging**
