### PR TITLE
release: 440.82

### PR DESCRIPTION
**Pull request by mmstick**
https://www.nvidia.com/Download/driverResults.aspx/159360/en-us

### CODE REVIEW

**Comment by MattInternet** [comment]
Is there a normal amount of time between when PRs for these are opened to when they get merged? In the history I've seen it range from 3 days to a month, just curious and excited to play doom eternal on pop-os :)

**Comment by jackpot51** [comment]
@MattInternet it depends on the changes. If you absolutely want to have this driver, you can follow these instructions to add this staging repository

```
git clone https://github.com/pop-os/pop
cd pop
./scripts/apt add 440.82
```

After it is released, run:
```
./scripts/apt remove 440.82
```

**Comment by MattInternet** [comment]
> @MattInternet it depends on the changes. If you absolutely want to have this driver, you can follow these instructions to add this staging repository
> 
> ```
> git clone https://github.com/pop-os/pop
> cd pop
> ./scripts/apt add 440.82
> ```
> 
> After it is released, run:
> 
> ```
> ./scripts/apt remove 440.82
> ```

Thank you!

**Comment by leviport** [comment]
# Here is what has been tested:

## Pop 18.04:
- [x] addw1
- [x] thelio-r2 w/2080

## Pop 19.10:
- [x] addw1
- [x] thelio-r2 w/RTX 2080
- [x] custom built desktop w/GTX 970

## Pop 20.04:
- [x] addw1
- [x] thelio-r2 w/2080
- [x] oryp4

## Ubuntu 18.04:
- [x] addw1
- [x] thelio-r2 w/2080

# Here is what has not been tested:

## Ubuntu 20.04
- [ ] addw1
- [ ] thelio-r2 w/2080


Once things are testable in Ubuntu 20.04, I will take another look.

**Comment by jackpot51** [comment]
This built for Ubuntu 20.04 - what's the issue?

**Pull request merged**
