### PR TITLE
NVIDIA 525.116.03

### PR DESCRIPTION
**Pull request by 13r0ck**
https://www.nvidia.com/Download/driverResults.aspx/204639/en-us/

### CODE REVIEW

**Comment by n3m0-22** [comment]
So far regression testing has passed on Pop 22.04 on gaze15, orpy4, and GeForce RTX 3060 (Desktop). Pop 20.04 has passed as well, but the gnome-shell update in master is needed again for Steam to start in NVIDIA mode. I will update with Ubuntu testing once finished.

**Comment by leviport** [comment]
It looks like the Pop 20.04 packages we need to release aren't building on Launchpad. Until those are released, this driver will break stuff on Pop 20.04.

**Comment by gabriele2000** [comment]
What about 535?
At this point, 525 is kinda outdated, since 535 has cool stuff in the changelog.

**Comment by 13r0ck** [comment]
@gabriele2000  530 is on the few features branch, 525 is still nvidia's production branch.
This was waiting on QA review for https://github.com/pop-os/systemd/pull/35

But this is outdated for 525, [525.116.04](https://www.nvidia.com/Download/driverResults.aspx/204837/en-us/) is out now. So I will open that and close this shortly.

**Comment by 13r0ck** [comment]
https://github.com/pop-os/nvidia-graphics-drivers/pull/183

**Pull request closed without merging**
