### PR TITLE
NVIDIA 525.89.02

### PR DESCRIPTION
**Pull request by 13r0ck**
https://www.nvidia.com/Download/driverResults.aspx/199656/en-us/

### CODE REVIEW

**Review by n3m0-22 — APPROVED** [review]
Testing as passed for Pop 22.04.
[nvidia-pop-22.04-testing.txt](https://github.com/pop-os/nvidia-graphics-drivers/files/10818069/nvidia-pop-22.04-testing.txt)

On Pop 20.04 Steam will only launch from the terminal in NVIDIA graphics mode. Installing the update to `gnome-shell` in `master` fixes the issue.

**Review by n3m0-22 — COMMENTED** [review]
Pop 20.04 passed testing.
[nvidia-pop-20.04-testing.txt](https://github.com/pop-os/nvidia-graphics-drivers/files/10818769/nvidia-pop-20.04-testing.txt)

**Comment by n3m0-22** [comment]
Ubuntu 20.04 and 22.04 passed all testing.

Note: Ubuntu 22.04 required `gnome-shell` to be updated from master to start Steam in NVIDIA graphics mode.

[nvidia-ubuntu-20.04-testing.txt](https://github.com/pop-os/nvidia-graphics-drivers/files/10828292/nvidia-ubuntu-20.04-testing.txt)
[nvidia-ubuntu-22.04-testing.txt](https://github.com/pop-os/nvidia-graphics-drivers/files/10828293/nvidia-ubuntu-22.04-testing.txt)

**Comment by 13r0ck** [comment]
@n3m0-22 Then we will have to release our gnome shell version on ubuntu.

We will do a repo-release next week before this is ready, and please double check after that.

**Comment by 13r0ck** [comment]
https://github.com/pop-os/pop/pull/2810

**Comment by n3m0-22** [comment]
The update to `gnome-shell` has resolved the issue of Steam not launching in NVIDIA graphics mode for Ubuntu 22.04. The same update for `gnome-shell` will need to be released for Pop 20.04 as noted above to resolve the same issue.

> Testing passed for Pop 22.04. [nvidia-pop-22.04-testing.txt](https://github.com/pop-os/nvidia-graphics-drivers/files/10818069/nvidia-pop-22.04-testing.txt)
> 
> On Pop 20.04 Steam will only launch from the terminal in NVIDIA graphics mode. Installing the update to `gnome-shell` in `master` fixes the issue.

**Comment by 13r0ck** [comment]
OOf, releasing the same gnome-shell version for focal is not going to work without a ton of rebaseing...
```
The following packages have unmet dependencies:
 sbuild-build-depends-main-dummy : Depends: debhelper-compat (= 13)
                                   Depends: gir1.2-gweather-3.0 (>= 40.0) but it is not going to be installed
                                   Depends: gnome-settings-daemon-common (>= 40~) but it is not going to be installed
                                   Depends: gsettings-desktop-schemas-dev (>= 42~beta) but 3.36.0-1ubuntu1 is to be installed
                                   Depends: libgjs-dev (>= 1.71.1) but it is not going to be installed
                                   Depends: libgnome-bluetooth-3.0-dev (>= 3.9.0) but it is not installable
                                   Depends: libgtk-4-dev but it is not installable
                                   Depends: libmutter-10-dev (>= 42.0) but it is not installable
                                   Depends: libmutter-test-10 (>= 42.0) but it is not installable
                                   Depends: libpipewire-0.3-dev (>= 0.3.10) but it is not installable
                                   Depends: meson (>= 0.58.0) but it is not going to be installed
                                   Depends: mutter (>= 42.0) but it is not going to be installed
```

I guess I will have to try and find the exact commit :crossed_fingers:

**Comment by 13r0ck** [comment]
When steam isn't working is there any useful log output?

**Comment by n3m0-22** [comment]
Steam logs:

[failed-gui-launch.txt](https://github.com/pop-os/nvidia-graphics-drivers/files/10854863/failed-gui-launch.txt)

[successful-cli-launch.txt](https://github.com/pop-os/nvidia-graphics-drivers/files/10854864/successful-cli-launch.txt)

**Comment by 13r0ck** [comment]
gnome shell `3.36.9-0ubuntu0.20.04.2pop1` wasn't released for focal, but now is. That fixes the steam bug on my focal machine.

**Comment by n3m0-22** [comment]
> gnome shell `3.36.9-0ubuntu0.20.04.2pop1` wasn't released for focal, but now is. That fixes the steam bug on my focal machine.

This has fix the issue for me as well. I retested in each graphics mode with Steam, and have seen no regressions.

I think this is good to go after desktop testing.

**Comment by XV-02** [comment]
I'll check desktop behaviour right now.

**Comment by XV-02** [comment]
Desktop Pop and Ubuntu 22.04 looking good. Just looking at Focal.

**Comment by XV-02** [comment]
@n3m0-22 This PR is looking good on both Focal and Jammy on desktop. If you're good with it on laptops, you should be good to approve it.

**Review by n3m0-22 — APPROVED** [review]
@XV-02 Has confirmed this is working on the `oryp10` as well.

**Review by jackpot51 — APPROVED** [review]

**Pull request merged**
