### PR TITLE
feat: 450.66 release

### PR DESCRIPTION
**Pull request by mmstick**
Currently testing on the oryp2

### CODE REVIEW

**Comment by leviport** [comment]
I'm seeing the same bug I saw with 450.57: https://github.com/pop-os/nvidia-graphics-drivers/pull/52#issuecomment-658199651

I'm only seeing it in Hybrid mode, after adding the 450.51 patch to enable reverse prime offloading. Could the issue be with reverse prime instead of the driver itself? 

I'm going to remove 450.51 and test. If this driver is okay without reverse prime, we might be able to merge it and worry about reverse prime independently.

**Comment by mmstick** [comment]
I wonder if NVIDIA is aware that their long-lived driver has this bug.

**Comment by geodro** [comment]
Any updates on this, or how can we help test it?

**Comment by mmstick** [comment]
@geodro It's already been tested. The 450.66 driver is a bust, so we must wait until NVIDIA releases a new driver, and hope that it has resolved this regression.

**Comment by jackpot51** [comment]
Obsolete by #57

**Comment by Redbatman89** [comment]
I had to revert back to 440.100, the new driver was making vulkan shaders take too long to process.

**Pull request closed without merging**
