### PR TITLE
Nvidia 545.29.02

### PR DESCRIPTION
**Pull request by mmstick**
Replaces #193

### CODE REVIEW

**Review by XV-02 — APPROVED** [review]
This is looking stable, and neither Levi nor I are spotting regressions. Calling it good.

**Comment by leviport** [comment]
Oh, the build failures on Focal might be an issue. If we want to make a `master_jammy`, that's probably fine for now.

**Comment by mmstick** [comment]
Nevermind. I found a way to conditionally include/exclude installation files based on release version.

**Review by jackpot51 — APPROVED** [review]

**Review by leviport — APPROVED** [review]
Still good on Jammy, but also now good on Focal.

**Comment by gabriele2000** [comment]
I don't know if it's only my problem, but I cannot open any game now.
Vulkan error -2 and similar stuff.

**Comment by leviport** [comment]
@gabriele2000 we haven't released this yet. Are you running the staging branch?

**Comment by gabriele2000** [comment]
> Ah perhaps you need this then: [pop-os/egl-wayland#1](https://github.com/pop-os/egl-wayland/pull/1)
> 
> Since Wayland is still non-default on Pop, it hasn't been as high of a priority. Let us know if it works though, any help testing is always welcome.

I'm afraid my inability to package this one and the "updated" v545 driver (the other branch) will have to make me use X11 again until this will be sorted, after more than one year.

It's an abomination, let me tell you (X11, of course).

**Comment by leviport** [comment]
You can add the staging branch for that PR like this:
```
apt-manage add popdev:egl-wayland
```
and then install updates normally. 

To remove the staging branch (it will start 404ing once the PR is merged and the branch is deleted), use this command:
```
apt-manage remove popdev-egl-wayland
```
(note that the `:` turns into a `-` when you're removing it)

**Comment by gabriele2000** [comment]
> You can add the staging branch for that PR like this:
> 
> ```
> apt-manage add popdev:egl-wayland
> ```
> 
> and then install updates normally.

Thanks to you I've understood this method fully, really, thanks!
Unfortunately both `wayland_client` and `egl-wayland` doesn't fix the problem, I guess there's something I'm overlooking here...

**Comment by mmstick** [comment]
You could try out the COSMIC desktop environment to see if it's something in your GNOME Wayland session.

**Comment by gabriele2000** [comment]
> You could try out the COSMIC desktop environment to see if it's something in your GNOME Wayland session.

Yes, I updated my previous comment to reflect the success of this operation, which I tried almost immediately after sending it.

**Pull request merged**
