### PR TITLE
NVIDIA 510.73.05

### PR DESCRIPTION
**Pull request by jackpot51**
https://www.nvidia.com/Download/driverResults.aspx/188994/en-us

### CODE REVIEW

**Comment by n3m0-22** [comment]
Results look good so far. All testing passed for `gaze15` on `22.04`. This fixes the fractional scaling issues seen in [#149](https://github.com/pop-os/nvidia-graphics-drivers/issues/149).
[nvidia-510.75.05_gaze15.txt](https://github.com/pop-os/nvidia-graphics-drivers/files/8765656/nvidia-510.75.05_gaze15.txt)

**Comment by XV-02** [comment]
Fractional scaling on Display Port isn't functioning correctly. At 125% fractional scale for the external monitor, the actual workspace extends significantly beyond the physical screen boundaries.

**Comment by n3m0-22** [comment]
`21.10` on `gaze15` all tests except for fractional scaling on an external monitor using mDP passed. It looks exactly the same as #149. Fractional scaling on an external monitor through HDMI is fine.

**Comment by n3m0-22** [comment]
`22.04` and `21.10` on `orpy4` all tests passed except for fractional scaling on an external monitor. Problems with both HDMI and mDP. Normal 100% and 200% scaling also not working for external display.

**Review by n3m0-22 — APPROVED** [review]

**Review by 13r0ck — APPROVED** [review]

**Pull request merged**
