### PR TITLE
NVIDIA 525.85.05

### PR DESCRIPTION
**Pull request by 13r0ck**

### CODE REVIEW

**Review by jackpot51 — APPROVED** [review]

**Review by n3m0-22 — COMMENTED** [review]
Testing passed for `Pop 22.04` on `gaze15` and `orpy4`

[nvidia-525.85.05-pop-22.04-oryp4.txt](https://github.com/pop-os/nvidia-graphics-drivers/files/10484502/nvidia-525.85.05-pop-22.04-oryp4.txt)
[nvidia-525.85.05-pop-22.04-gaze15.txt](https://github.com/pop-os/nvidia-graphics-drivers/files/10484503/nvidia-525.85.05-pop-22.04-gaze15.txt)

I will update with results from Pop `20.04`, Ubuntu `20.04`, and `22.04`.

Update:

`Pop 20.04` passed all testing on the same machines.

[nvidia-525.85.05-pop-20.04-gaze15.txt](https://github.com/pop-os/nvidia-graphics-drivers/files/10493242/nvidia-525.85.05-pop-20.04-gaze15.txt)
[nvidia-525.85.05-pop-20.04-oryp4.txt](https://github.com/pop-os/nvidia-graphics-drivers/files/10493243/nvidia-525.85.05-pop-20.04-oryp4.txt)

**Comment by XV-02** [comment]
On desktop, everything looks good.
[nvidia-525.85.05-Pop-2204-MegaR1.txt](https://github.com/pop-os/nvidia-graphics-drivers/files/10523328/nvidia-525.85.05-Pop-2204-desktop.txt)

[nvidia-525.85.05-Ubuntu-2204-MegaR1.txt](https://github.com/pop-os/nvidia-graphics-drivers/files/10523891/nvidia-525.85.05-Ubuntu-2204-MegaR1.txt)

Oryp10 didn't show any regressions on a smoke test (they've been temperamental lately)

No improvement on MiraB4 with 3060, but no obvious regressions either. 

Not seeing any issues with plymouth functionality.

**Comment by n3m0-22** [comment]
There is an update to `gnome-shell` specifically `209ba51` in master that is not building on launchpad. This will need to be fixed or `20.04` users will need to add master to run Steam in NVIDIA graphics mode.

**Review by n3m0-22 — APPROVED** [review]
The Steam NVIDIA issue has be resolved by https://github.com/pop-os/gnome-shell/pull/128.

**Pull request merged**
