### PR TITLE
510.60.02

### PR DESCRIPTION
**Pull request by jackpot51**
https://www.nvidia.com/Download/driverResults.aspx/187162/en-us

### CODE REVIEW

**Comment by XV-02** [comment]
When attempting to update through pop_shop from 470, 510.60.02 throws up a dependence error for the previous 510 driver iteration, and provides no way through pop-shop to do the intermediary update.

**Comment by jackpot51** [comment]
@XV-02 can you provide a screenshot?

**Comment by linuxgnuru** [comment]
Which Pop version are you running?

**Comment by XV-02** [comment]
> Which Pop version are you running?

I'm using 20.04. I suspect that the issue would persist regardless. Currently the 20.04 iso ships with 470.

**Comment by jackpot51** [comment]
@XV-02 I hope the latest changes fix those issues. If not, it may be worth it to just release this on 22.04

**Review by n3m0-22 — COMMENTED** [review]
After testing with 20.04 I have found the error persists even after adding this upgrade. I can reproduce the error both with and without the upgrade.

nvidia_error

I was not able to purge the driver as suggested receiving this error instead.

```
sudo apt purge nvidia-*
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package nvidia-installer.log
E: Couldn't find any package by glob 'nvidia-installer.log'
```
 After trying to update with ```NVIDIA-Linux-x86_64-510.60.02.run``` I came across this error.

nvidia_error_driver_install

When trying to install from the terminal I was met with the same missing dependencies message. The only way I was able to upgrade was to install the first missing dependency with
```sudo apt install libnvidia-gl-510``` this ended up removing 470 and installing 510.

The one odd thing was even after this upgrade and a reboot the 510 driver still showed in pop-shop as an upgrade but upon clicking install there was just a quick flash and then it shows as upgraded there too.

After the upgrade I have so far tested the following with all working:
1.  switching between graphics modes
2.  unigine
3.  steam both native and proton
4.  hdmi with sound
5.  defaulting to external monitor when laptop is closed and switching back on open
6.  suspend and wake

**Comment by jackpot51** [comment]
I pushed this to master_jammy to unblock https://github.com/pop-os/beta/issues/372. I need help diagnosing the 20.04 packaging issues (cc: @13r0ck) since I don't have an NVIDIA system I can wipe with 20.04 right now.

**Comment by n3m0-22** [comment]
The problem is still there in 20.04.

1. clean install of 20.04
2. ```sudo apt update && sudo apt upgrade```
3. reboot
4. ```./pop/scripts/apt add nvidia-510.60.02```
5. ```sudo apt update```
6. nvidia 510 disappears from pop-shop
7. reboot
8. nvidia 510 still not showing in pop-shop
9. ```sudo apt update```
10. nvidia 510 now shows in pop-shop
11. click install and the following error shows

```
The following packages have unmet dependencies:
  nvidia-driver-510: Depends: libnvidia-gl-510 (= 510.60.02-1pop0~1649099333~20.04~aedf526) but it is not going to be installed
                     Depends: nvidia-dkms-510 (>= 510.60.02)
                     Depends: nvidia-kernel-common-510 (>= 510.60.02) but it is not going to be installed
                     Depends: nvidia-kernel-source-510 (= 510.60.02-1pop0~1649099333~20.04~aedf526) but it is not going to be installed
                     Depends: libnvidia-extra-510 (= 510.60.02-1pop0~1649099333~20.04~aedf526) but it is not going to be installed
                     Depends: libnvidia-decode-510 (= 510.60.02-1pop0~1649099333~20.04~aedf526) but it is not going to be installed
                     Depends: libnvidia-encode-510 (= 510.60.02-1pop0~1649099333~20.04~aedf526) but it is not going to be installed
                     Depends: xserver-xorg-video-nvidia-510 (= 510.60.02-1pop0~1649099333~20.04~aedf526) but it is not going to be installed
                     Depends: libnvidia-cfg1-510 (= 510.60.02-1pop0~1649099333~20.04~aedf526) but it is not going to be installed
                     Depends: libnvidia-fbc1-510 (= 510.60.02-1pop0~1649099333~20.04~aedf526) but it is not going to be installed
                     Recommends: libnvidia-compute-510:i386 (= 510.60.02-1pop0~1649099333~20.04~aedf526)
                     Recommends: libnvidia-decode-510:i386 (= 510.60.02-1pop0~1649099333~20.04~aedf526)
                     Recommends: libnvidia-encode-510:i386 (= 510.60.02-1pop0~1649099333~20.04~aedf526)
                     Recommends: libnvidia-fbc1-510:i386 (= 510.60.02-1pop0~1649099333~20.04~aedf526)
                     Recommends: libnvidia-gl-510:i386 (= 510.60.02-1pop0~1649099333~20.04~aedf526)
```

**Comment by n3m0-22** [comment]
I tried the following

1. ```sudo apt purge nvidia-*```
2. ```sudo apt autoremove```
3. reboot
4. ```sudo apt install nvidia-driver-470```
5. reboot
6. 510 does not show up in pop-shop
7. upgrading from the terminal with ```sudo apt install nvidia-driver-510`` no longer shows issues

**Comment by n3m0-22** [comment]
*Correction* :
After running ```sudo apt update``` 510 is back in pop-shop and installs with no problems

**Review by n3m0-22 — CHANGES_REQUESTED** [review]
#### I was able to get this working in ```20.04```, but only by using ```pop-os_20.04_amd64_nvidia_debug_172.iso```. It still won't work with ```pop-os_20.04_amd64_nvidia_39.iso```.  

### Steps to reproduce
1. Fresh install with ```pop-os_20.04_amd64_intel_debug_172.iso```
2. After initial setup ```sudo apt purge ~nnvidia```
3. ```sudo apt autoremove```
4. Reboot
5. ```sudo apt install nvidia-driver-470```
6. Reboot
7. ```sudo apt update```
8. Open pop-shop *click to install* ```510.54```
9. Reboot
10. ```./pop/scripts/apt add nvidia-510.60.02```
11. ```sudo apt update```
12. Open pop-shop ```510.60.02``` will be under Operating System Updates *click to install*
13. Reboot

### Screenshots documenting the process
Screenshot from 2022-04-13 11-37-19
Screenshot from 2022-04-13 11-37-35
Screenshot from 2022-04-13 11-41-09
Screenshot from 2022-04-13 11-41-54
Screenshot from 2022-04-13 11-43-57
Screenshot from 2022-04-13 11-44-32
Screenshot from 2022-04-13 11-44-57
Screenshot from 2022-04-13 11-45-20
Screenshot from 2022-04-13 11-50-04

**Comment by jackpot51** [comment]
Obsolete, see #147

**Pull request closed without merging**
