### PR TITLE
Add arm64 driver

### PR DESCRIPTION
**Pull request by jackpot51**
This adds the arm64 driver, for use by Astra

### CODE REVIEW

**Review by wash2 — APPROVED** [review]

**Review by leviport — APPROVED** [review]

**Comment by leviport** [comment]
This installs and works fine on my oryp9 running Jammy. Are the i386 build failures on Focal a concern?

**Comment by jackpot51** [comment]
@leviport we could branch off focal. It is missing libnvidia-egl-wayland1 for i386.

**Comment by jackpot51** [comment]
Latest commit may fix it?

**Comment by jackpot51** [comment]
@leviport everything is built this time

**Review by wash2 — APPROVED** [review]

**Review by leviport — APPROVED** [review]
Looking great on my oryp9

**Pull request merged**
