### PR TITLE
470.42.01 beta: https://forums.developer.nvidia.com/t/linux-solaris-and-freebsd-driver-470-42-01-beta/181536

### PR DESCRIPTION
**Pull request by leviport**

### CODE REVIEW

**Comment by jacobgkau** [comment]
- [X] Installs with a regular `apt upgrade`.
-  oryp7 OLED (3070), Pop!_OS 20.04 LTS:
    - [X] Graphics
    - [X] Compute
    - [X] Display configuration & audio through display (HDMI, DisplayPort over USB-C)
    - [X] Suspend/resume, including while playing Firefox video
    - [ ] Graphics switching & modes (Compute mode issue was pre-existing: https://github.com/system76/firmware-open/issues/160)
- galp5 (1650 Ti), Pop!_OS 21.04:
    - [X] Graphics
    - [X] Compute
    - [X] Display configuration & audio through display (HDMI, DisplayPort over USB-C)
    - [X] Suspend/resume, including while playing Firefox video
    - [X] Graphics switching & modes

**Comment by jackpot51** [comment]
For users who want to test this out:

## Install
```
git clone https://github.com/pop-os/pop.git
cd pop
./scripts/apt add 470.42
sudo apt update
sudo apt full-upgrade
```

## Uninstall (skip first step if already done in Install)
```
git clone https://github.com/pop-os/pop.git
cd pop
./scripts/apt remove 470.42
sudo apt update
sudo apt full-upgrade
```

**Comment by cybik** [comment]
# Test Writeup

## Issue

Using the latest 470.xx drivers, 2 out of 3 of my monitors exhibit a strange backlight behaviour where the backlight level seems to wave, essentially causing sort of a light flickering that becomes bothersome within a minute.

## Hardware configuration

* Non-pop hardware
* i7 8700k
* nVidia RTX3060Ti
* Pop 21.04 beta
* nVidia 470.42
* 3 screens, two of which Adaptive sync enabled (One true GSync, one Forced GSync)
  * The third screen not being GSync and not exhibiting this behaviour, it's possible the issue is related to adaptive sync.

## Software configuration

### Behaviour tested on
* SDDM + KDE/KF5 + KWin, without and with modesetting (boot option)
* GDM3 + Gnome Shell, without modesetting (boot option, or specifically lack thereof)

### Kernels tested
* xanmod1-calcule 5.12.10
* baseline Pop_OS 5.11.0-7614

**Comment by SlickMcRunFast** [comment]
> For users who want to test this out:
> 
> ## Install
> ```
> git clone https://github.com/pop-os/pop.git
> cd pop
> ./scripts/apt add 470.42
> sudo apt update
> sudo apt full-upgrade
> ```
> 
> ## Uninstall (skip first step if already done in Install)
> ```
> git clone https://github.com/pop-os/pop.git
> cd pop
> ./scripts/apt remove 470.42
> sudo apt update
> sudo apt full-upgrade
> ```
> 
> Please list any issues that are not present in the prior version as a comment here.

pop 21.04 beta, 2070 super

With 470 beta, GPU intensive processes lock up my system. Ran "7 days to die native Linux client" and had to force reboot. Ran SteamVR and launching a game causes the same lock up. Couldn't even get to the tty5. Revert to 465 and everything runs well again. Possibly something from my failed attempt at installing the .run file from nvidia before getting it from the PPA.

While reverting the uninstall script didn't work for me so I manually removed the apt source and purged nvidia*470*.

**Comment by cybik** [comment]
> While reverting the uninstall script didn't work for me so I manually removed the apt source and purged nvidia_470_.

Echoing @SlickMcRunFast, reverting to 470 was painful in my case because of a systemd hibernate script. removing nvidia-driver-470 manually, *then* downgrading the nVidia packages to 465, worked properly.

**Comment by bflanagin** [comment]
470.57.02 has been released as stable. We'll probably need to update this to reflect that or close this and then make a new one. (Not sure which is easier.)

**Comment by leviport** [comment]
I've opened a PR for the new version here: https://github.com/pop-os/nvidia-graphics-drivers/pull/114

I'm going to keep this one open for now, in case there are a lot of users with this version installed.

**Comment by bflanagin** [comment]
Closing this PR for the newer version. For those that helped us test things be sure to run these commands to remove it from your system if you haven't done so already.

```
git clone https://github.com/pop-os/pop.git
cd pop
./scripts/apt remove 470.42
sudo apt update
sudo apt full-upgrade

```

**Pull request closed without merging**
