### PR TITLE
460.56: https://www.nvidia.com/download/driverResults.aspx/170804

### PR DESCRIPTION
**Pull request by mmstick**

### CODE REVIEW

**Review by bflanagin — COMMENTED** [review]
On 20.10 gaze15 in Nvidia mode flatpaks fail:

Read prefs: /home/bflanagin/.var/app/org.blender.Blender/config/blender/2.91/config/userpref.blend
/home/sources/buildbot-worker-linux_centos7/linux_291/blender.git/intern/ghost/intern/GHOST_WindowX11.cpp:206: X11 glXChooseVisual() failed, verify working openGL system!
initial window could not find the GLX extension

Doing more testing, will delete if I find it to be me and not the driver.

**Comment by mmstick** [comment]
@bflanagin Flatpak requires that you have the same version of the driver installed as a flatpak. `flatpak update` should fetch the Flatpak driver if they have packaged it yet.

**Comment by bflanagin** [comment]
@mmstick then we need to wait until its available for flatpak to catch up

**Review by jackpot51 — APPROVED** [review]

**Comment by jackpot51** [comment]
https://github.com/flathub/org.freedesktop.Platform.GL.nvidia/commit/0b52e64893745391e73f0b6eb216584e2564bde7

**Review by bflanagin — COMMENTED** [review]
The flatpak update finally hit flathub sometime last night. 
All regression tests pass on gaze15 (gtx 1660 ti). 
@leviport @jacobgkau will need to their blessings before approval

**Comment by jacobgkau** [comment]
- Installs with a normal `apt upgrade`.
- oryp7 (3060):
  - [X] Graphics
  - [X] Compute
  - [X] Display configuration & audio through display
  - [X] Suspend/resume, including while playing Firefox video
  - [ ] Graphics switching & modes (Compute mode issue being worked on elsewhere, not a regression)
- serw12 (1660 Ti)
  - [X] Graphics
  - [X] Compute
  - [X] Display configuration & audio through display
  - [X] Suspend/resume, including while playing Firefox video
- galp5 (1650):
  - [X] Graphics
  - [X] Compute
  - [X] Display configuration & audio through display
  - [X] Suspend/resume, including while playing Firefox video
  - [X] Graphics switching & modes

Not seeing any concerns on laptops. I assume @leviport will want to check some desktop cards.

**Review by leviport — APPROVED** [review]
Looking good on 3060Ti and 2080Ti in thelio-b2

**Pull request merged**
