### PR TITLE
465.27: https://www.nvidia.com/Download/driverResults.aspx/174582/en-us

### PR DESCRIPTION
**Pull request by mmstick**

### CODE REVIEW

**Comment by jackpot51** [comment]
Is the run file missing again?

**Comment by mmstick** [comment]
Uploading it now

**Review by jackpot51 — APPROVED** [review]

**Comment by bflanagin** [comment]
Initial install left steam unable to open. Purging and reinstalling fixed the issue.

**Comment by bflanagin** [comment]
Gaze15 1660 ti Pop 21.04

## Standard Tests

- [x] installs 

## Single display 

- [x] Hybrid Mode
- [x] Dedicated Mode
- [x] Integraded Mode
- [x] Compute Mode

## Multiple Displays

- [x] Hybrid Mode
- [x] Dedicated Mode

- [] Integrated mode
- [] Compute Mode

## Software tests

- [x] Steam client launches, 32bit proton game works
- [x] Graphics accelerated Flatpak works 

## Suspend tests: to test for screen corruption
- [ ] Hybrid (still needs testing)
- [ ] Integrated (still needs testing)
- [ ] Dedicated (still needs testing)

**Comment by jackpot51** [comment]
Obsoleted by #106

**Pull request closed without merging**
